name: francis j duggan
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5989201876800507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0
  lightness: 0.4934537010267377
  saturation: 0.7898614560253918
  rhythmicContrast: 0.23865537904202938
purpose: []
