name: ' '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.0578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6c8c9'
    - '#faf8f8'
    - '#726b66'
    - '#333746'
    - '#f4a98d'
  brandStrength: 1
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
