name: ' '
favicon: null
layout_spectrum: 0.74952
typography_spectrum: 0.0578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7e2ea'
    - '#92acb3'
    - '#0f1220'
    - '#4d717b'
    - '#c08b4d'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
